### ISSUE TITLE
Not staying cleared in latest TweetDeck

### ISSUE THREAD

**Issue by aaronjbaptiste** [daniula/TweetDeck-Clear-Column#1]
Press Alt+x to clear a column, it clears but then reloading the page simply brings the items back again.

Chrome OSX: Version 42.0.2311.152 (64-bit)

**Comment by daniula** [comment]
That is intended. If you clear your column by mistake you can easily revert it by just refreshing page.
Also it's simpler to implement it this way.

Feel free to add this feature with some simple config, so users can choose which way they prefer.

**Comment by aaronjbaptiste** [comment]
ah right, that makes sense. Thanks
